### ISSUE TITLE
print("No fileID found for %s" % fileinfo_str(fileinfo), file=sys.stderr)

### ISSUE THREAD

**Issue by elalemanyo** [wiggin15/whatsapp_history#2] opened 2015-04-30 15:07 UTC
Hi,

I am trying to use your script, but i am getting this error:

```
[03:50:22] [/www/whatsapp_history] [master]
-> % python iphone_history.py
Traceback (most recent call last):
  File "iphone_history.py", line 6, in <module>
    import mbdb
  File "/www/whatsapp_history/mbdb.py", line 68
    print("No fileID found for %s" % fileinfo_str(fileinfo), file=sys.stderr)
                                                                 ^
SyntaxError: invalid syntax
```

Can you help me with that?

Thanks!

**Comment by wiggin15** [comment] 2015-04-30 16:21
The script was meant to run on Python 3 only.
I just added Python 2 support. Please try to run now. Thanks.

**Comment by elalemanyo** [comment] 2015-05-02 11:19
I try it again, and now I get this error:

```
-> % python iphone_history.py
Could not find date of backup from /Users/[user name]/Library/Application Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c
```

Thanks

**Comment by wiggin15** [comment] 2015-05-02 13:07
That's strange. The file Info.plist in that directory should contain the date...
Can you please run:

    ls -l ~/Library/Application\ Support/MobileSync/Backup/

and

    cat ~/Library/Application\ Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c/Info.plist | grep -i date

and paste the output?

**Comment by elalemanyo** [comment] 2015-05-02 13:14
The first command give me the list of all my backups, but the second do not give any output.

**Comment by wiggin15** [comment] 2015-05-02 14:03
It would be helpful if you can open the Info.plist file (`~/Library/Application\ Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c/Info.plist`) and see if the date is there in any other format (maybe search for "2015" in it). In the meantime I pushed a fix that will ignore backups when the date is not found (maybe it happens only on one of your backups and the others are ok?) Try to use it now.
Thanks for the patience while fixing these problems.

**Comment by elalemanyo** [comment] 2015-05-02 14:08
I did a pull and try again:

```
-> % python iphone_history.py
WARNING: Could not find date of backup from ~/Library/Application Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c. Assigning oldest date
Traceback (most recent call last):
  File "iphone_history.py", line 94, in <module>
    main()
  File "iphone_history.py", line 88, in main
    backup_extractor = BackupExtractor()
  File "iphone_history.py", line 13, in __init__
    backup_folder = self._get_backup_folder()
  File "iphone_history.py", line 60, in _get_backup_folder
    backup_folders_with_times = [(d, self._backup_time(d)) for d in list_of_backups]
  File "iphone_history.py", line 33, in _backup_time
    info_data = open(info_file, "r").read()
IOError: [Errno 2] No such file or directory: '~/Library/Application Support/MobileSync/Backup/Tenorshare_f94acf05af8e28476576e7a2487aff402d6a2c2c/Info.plist'
```

Thanks!

**Comment by wiggin15** [comment] 2015-05-02 14:33
Ok. Another strange backup :) Try now...?

**Comment by elalemanyo** [comment] 2015-05-02 14:46
Now works, but not with every backup, why?
I get this error at the beginning:
```
-> % python iphone_history.py
WARNING: Could not find date of backup from ~/Library/Application Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c. Assigning oldest date
WARNING: No Info.plist in backup ~/Library/Application Support/MobileSync/Backup/Tenorshare_f94acf05af8e28476576e7a2487aff402d6a2c2c. Assigning oldest date
WhatsApp   [##########] 100.0% done
SMS        [##########] 100.0% done
```
Any Idea why? Can I fix this Backups?

I think will be great to add output_* to the .gitignore.

Thanks!

**Comment by wiggin15** [comment] 2015-05-02 15:02
The script looks for the newest backup so the two warnings aren't a real problem (unless they are newer than the backup used). It should only run once, so it looks like it's working correctly :)

Maybe the backups are very old? (try to run ls -ltr on  ~/Library/Application Support/MobileSync and see where f94acf05af8e28476576e7a2487aff402d6a2c2c shows up). Or maybe it has to do with Tenorshare? (it's in the name of the backup).

I'll update .gitignore

**Comment by elalemanyo** [comment] 2015-05-02 15:07
Ok, thank you for all your help!
it is possible to use a backup that is not the newest?

Thanks

**Comment by wiggin15** [comment] 2015-05-02 18:23
There is no way to do this right now. The idea is that newer backups should have all the messages from older backups. You can change the code if you want to change this behavior.

**Comment by elalemanyo** [comment] 2015-05-02 18:28
ok, but what happen if you have backups from more than one devices? Maybe will be great if you can select the backup that should be used.

Thanks!

**Comment by wiggin15** [comment] 2015-05-02 19:51
I added a branch "choose" for you.

    git pull
    git checkout choose

You will probably have two empty entires in the list because of the two backups that can't be parsed.

**Comment by elalemanyo** [comment] 2015-05-03 06:51
Thanks! The new branch works great. I think it is a great feature.
But i still having problems with two Backups, no Idea what is wrong with them.
That is the error I get when I choose them:

```
Traceback (most recent call last):
  File "iphone_history.py", line 119, in <module>
    main()
  File "iphone_history.py", line 116, in main
    lib_main(backup_extractor, lib)
  File "iphone_history.py", line 95, in lib_main
    existing_file_path = backup_extractor.get_file_path(domain, filename)
  File "iphone_history.py", line 64, in get_file_path
    return self._get_file_index().get((domain, filename), None)
  File "iphone_history.py", line 57, in _get_file_index
    domain = f['domain'].decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 93: ordinal not in range(128)
```
It is possible to fix the Backups and get the Whatsapp and SMS/iMessage?

Thanks for all your work!

**Comment by wiggin15** [comment] 2015-05-03 08:26
I don't know what's wrong with the backups... Maybe if you look inside `~/Library/Application\ Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c/Info.plist` you can try to see if there is anything strange about it?

The problem you posted is a different issue that I hope I just fixed. Try now?

**Comment by elalemanyo** [comment] 2015-05-03 13:19
Ok, I check the Info.plist and I think that something goes wrong:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AppleMobileBackup</key>
	<true/>
</dict>
</plist>
```

Is it possible to fix it, so I can get the Whatsapp and SMS/iMessage?

**Comment by wiggin15** [comment] 2015-05-03 21:55
I don't think it's possible to fix the file, but can you try to rerun the script with the latest code?

**Comment by elalemanyo** [comment] 2015-05-04 07:32
Here is the error that I am getting right now:

```
-> % python iphone_history.py
WARNING: no date found for backup folder ~/Library/Application Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c
WARNING: no device name found in backup folder ~/Library/Application Support/MobileSync/Backup/f94acf05af8e28476576e7a2487aff402d6a2c2c
WARNING: no Info.plist file found in backup folder ~/Library/Application Support/MobileSync/Backup/Tenorshare_f94acf05af8e28476576e7a2487aff402d6a2c2c
Choose backup:
1.  1970-01-01 01:00:00
2.  1970-01-01 01:00:00
3. iPhone 2014-12-28 12:09:38
4. iPhone 2014-12-28 13:15:21
5. iPhone 2014-12-28 14:39:38
6. iPhone (5) 2015-04-21 13:49:28
1
Traceback (most recent call last):
  File "iphone_history.py", line 119, in <module>
    main()
  File "iphone_history.py", line 116, in main
    lib_main(backup_extractor, lib)
  File "iphone_history.py", line 95, in lib_main
    existing_file_path = backup_extractor.get_file_path(domain, filename)
  File "iphone_history.py", line 64, in get_file_path
    return self._get_file_index().get((domain, filename), None)
  File "iphone_history.py", line 57, in _get_file_index
    domain = f['domain'].decode("utf-8")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 93: invalid start byte
```

**Comment by wiggin15** [comment] 2015-05-04 08:43
Sorry, I'm afraid I can't help any further.
Thanks for reporting a bunch of problems that are now fixed.

**Comment by elalemanyo** [comment] 2015-05-04 08:49
I thank you for all your work. Maybe I can copy the Info.plist from another backup, what do you think?

**Comment by wiggin15** [comment] 2015-05-04 09:35
The problem you are now having doesn't look like a problem with the plist file (although that file is indeed not in the correct format). Now it looks like yet another problem with the backup, this time with the encoding in the file index.

**Comment by wiggin15** [comment] 2015-05-04 09:37
I committed something that *might* help, but given the amount of issues with this backup I can't be sure any more. Give it another try.

**Comment by elalemanyo** [comment] 2015-05-04 09:44
Ok, now works with one of the Backups to get the SMS. On the other one I get the same error.
But I get on the first one a new error, I am not sure if all the bug that you are fixing are jut because my two "strange" Backups... sorry.

```
Could not find file in backup: AppDomainGroup-group.net.whatsapp.WhatsApp.shared/ChatStorage.sqlite
SMS        [##########] 100.0% done
```

Thanks

**Comment by wiggin15** [comment] 2015-05-04 18:48
Oh, much better. Now the problem is that the backup is a little old so the script is not using the correct path to the Whatsapp database. I will try to add support for both file paths (the old and the new) so that you can use this backup, but it's a bit more complicated than the other fixes.

To answer your question - I added 10 commits since you opened this issue, and about half are specific to the "strange backup".

**Comment by elalemanyo** [comment] 2015-05-05 04:48
Thank you very much for all the work!

**Comment by elalemanyo** [comment] 2015-05-05 17:47
Hi,

For one of the "old_backups" works great, but for the other one I get this error:

```
Traceback (most recent call last):
  File "iphone_history.py", line 119, in <module>
    main()
  File "iphone_history.py", line 116, in main
    lib_main(backup_extractor, lib)
  File "iphone_history.py", line 95, in lib_main
    existing_file_path = backup_extractor.get_file_path(domain, filename)
  File "iphone_history.py", line 64, in get_file_path
    return self._get_file_index().get((domain, filename), None)
  File "iphone_history.py", line 56, in _get_file_index
    for f in files_in_backup:
  File "/www/whatsapp_history/mbdb.py", line 69, in process_mbdb_file
    mbdb = process_mbdb_file_internal(fname)
  File "/www/whatsapp_history/mbdb.py", line 34, in process_mbdb_file_internal
    data = open(filename, "rb").read()
IOError: [Errno 2] No such file or directory: '~/Library/Application Support/MobileSync/Backup/Tenorshare_f94acf05af8e28476576e7a2487aff402d6a2c2c/Manifest.mbdb'
```

I am doing something wrong?

Thanks!

**Comment by wiggin15** [comment] 2015-05-05 17:54
That's a missing file in that backup that the script can't run without...
I think both backups are acutally the same though, so if it works on one you have the same output of the other. The two backups have the same ID (only a different prefix):
`Tenorshare_f94acf05af8e28476576e7a2487aff402d6a2c2c`
and `f94acf05af8e28476576e7a2487aff402d6a2c2c`. So If it worked on the first one, you don't really need it to work on the other.

Good to hear it finally works :)

**Comment by elalemanyo** [comment] 2015-05-05 18:12
They are backups from the same device, but the one with the prefix is older als the other one. So the output will be different. On the old one are the sms/whats_app that I need to get. May be I can move the missing file from one to the other, what do you think?

**Comment by wiggin15** [comment] 2015-05-05 18:17
You can try that (it's the Manifest.mbdb file), but I can't tell if that will work... I don't know why and how that backup is missing the files and how to handle it.

**Comment by elalemanyo** [comment] 2015-05-05 18:26
You are right, that didn't work....
```
Traceback (most recent call last):
  File "iphone_history.py", line 119, in <module>
    main()
  File "iphone_history.py", line 116, in main
    lib_main(backup_extractor, lib)
  File "iphone_history.py", line 104, in lib_main
    lib.main(backup_extractor)
  File "/www/whatsapp_history/whatsapp.py", line 112, in main
    c.execute("SELECT COUNT(*) FROM ZWACHATSESSION")
sqlite3.OperationalError: no such table: ZWACHATSESSION
```

**Comment by wiggin15** [comment] 2015-05-23 20:31
I think there's nothing more to do here. Thanks for helping to improve the script!

**Closed by wiggin15** 2015-05-23 20:31 UTC
